### PR TITLE
New approach for the plugin to process the pom model through ModelProcessor

### PR DESCRIPTION
**Pull request by xeagle2**
Thank you so much to take time to contribute to the project.

Before submitting the pull-request please ensure that you have first:
- [ ] read the [contribution guidelines](https://github.com/jgitver/jgitver-maven-plugin/blob/master/.github/CONTRIBUTING.md)
- [ ] rebased your branch over master
- [ ] verified that project is compiling and that tests pass: `mvn -Prun-its clean install`
- [ ] marked as closed (in the commit comments) all issues ID that this PR should correct
  …cessor

### CODE REVIEW

**Comment by McFoggy** [comment]
@xeagle2 Thx for the PR. 

I'll do the following for the integration:
- add you as contributor in the main pom
- set the all the headers with the Apache2 license
- correct the IT tests

once done I'll push in a branch so that you can review.
After that I'll modify the project do revert the old modes and introduce a new configuration mechanism.

**Comment by xeagle2** [comment]
Sounds good, thanks again and looking forward to see the new concept up.

**Comment by McFoggy** [comment]
@xeagle2 I have integrated your changes, corrected the tests & documented a bit further. Have a look at the [model branch](https://github.com/jgitver/jgitver-maven-plugin/tree/model) please.

**Comment by xeagle2** [comment]
@McFoggy, thanks for getting this managed. I scanned quickly the modifications from "model branch", looks good so far. Hopefully the tests are still green :) and the version could be released soon :+1:

**Pull request merged**
