### PR TITLE
Support for 'useMaxVersion' jgitver paramter

### PR DESCRIPTION
**Pull request by djarosz**

### CODE REVIEW

**Comment by McFoggy** [comment]
with jgitver/jgitver#53 I think this PR becomes obsolete. I think we do not need maxVersion property.

**Comment by djarosz** [comment]
If maxVersion semantics will be the default (and possibly only one behaviour) then You are right we do not need this parameter. My intentions for this parameter was keeping backward compatibility with current user configurations. I my case I need new behaviour because it makes difficult to keep consistent app versioning  when merging branches (i.e. fixes from production branches to development branches are currently done using cherry-picking which does not preserve history)

**Comment by McFoggy** [comment]
it will be the default behavior just wait for the resolution of jgitver/jgitver#53 and we'll be able to retest your use cases.

**Comment by McFoggy** [comment]
@djarosz latest jgitver-0.8.2 & jgitver-maven-plugin-1.4.0 deprecate this PR ; I'll thus close it.

Thanks again for your contribution that make the 2 above versions a reality.

**Pull request closed without merging**
