### PR TITLE
add option to resolve project.version in depdencencies section.

### LINKED ISSUE #129: replace project.version with value
maven knows ${project.version} and ${parent.project.version}. e.g for a project which has modules a and b, b depends on a one can use project.version. unfortunately on "mvn install" or "mvn deploy" the fields stay as is, $project.version.

if one wants to inherit something, $project.version is in there, not the parent projects version is displayed, but the version of the component. this may fail as it searches now the parent with the version of the child.

it would be nice if jgitver could replace the ${project.version} before install/depoy so no uncertainty is left which version to take.

### PR DESCRIPTION
**Pull request by michael-wirth**
This closes #129 - the `maven-flatten-plugin` is not a practical alternative to replace the ${project.version} variables in the pom.xml, as there is no option to just simply replace this specific variable.

Thank you so much to take time to contribute to the project.

Before submitting the pull-request please ensure that you have first:

- [x] read the [contribution guidelines](https://github.com/jgitver/jgitver-maven-plugin/blob/master/.github/CONTRIBUTING.md)
- [x] rebased your branch over master
- [x] verified that project is compiling and that tests pass: `mvn -Prun-its clean install`
- [x] marked as closed (in the commit comments) all issues ID that this PR should correct

### CODE REVIEW

**Comment by McFoggy** [comment]
@michael-wirth why is `maven-flatten-plugin` not a solution for your use case?

**Comment by michael-wirth** [comment]
@McFoggy because I don't want `maven-flatten-plugin` to rewrite my pom.xml and pull al dependencies from all parent pom.xml into the new pom.xml. I want to replace ONLY the `${project.version}` variable - nothing else should be done

**Comment by McFoggy** [comment]
I need to further think about this requirement. 

I am not sure yet jgitver should go this way.
Neither am I convinced that your expectations are valid ; If I read carefully what you reported in this [#129 comment](https://github.com/jgitver/jgitver-maven-plugin/issues/129#issuecomment-671929618) then I could reproduce your issue WITHOUT jgitver. Your problem might be that you break the parent/child contract instead of using a BOM file to fix/include dependencies.

My goal was really to get rid of the rewrite of the pom in favor of flatten-maven-plugin, not to to enhance this self rewrite further.

**Comment by michael-wirth** [comment]
@McFoggy I understand that you want to get rid of your own rewrite function. Then I have to look for another option to get the `pom.xml` right. I still believe this is a very important feature.

**Comment by dfournie** [comment]
Hello @michael-wirth, I've discovered jigtver plugin fews weeks ago, and decided to use it for a multi module , where parent project (bom) and submodules must have they version aligned. I ran into a very close problem when reusing the builded libs into another project.

I've tested a short modification of the jgitver maven plugin to resolve this issue.
Instead of derivate the usage of ${project.version}, i've added to the plugin the ability to expose the ${jgitver.calculated_version} in the resulting pom properties. As a consequence this property can be reused anywhere in the project (dependency management, submobules, etc...) to keep all modules with the version calculated by jgitver.
This may be another approach instead of rewriting all ${project.version}

**Comment by McFoggy** [comment]
Waiting for maven 4/5 that will distinguish the build pom from the consumer pom, the way to go is really `maven-flatten-plugin`.

look at https://github.com/jgitver/jgitver-maven-plugin/commit/e851ee7c3e081ab186349cee41fe5c027b86a6c9 comment

**Comment by dfournie** [comment]
@McFoggy as for @michael-wirth, I don't want a complete rewrite of the pom.xml provided by the `flatten-maven-plugin` for some reasons :
* Require to configure the plugin with its many options to have something near to the original pom
* I've not found a detailed documentation easily to know a to configure it
* Didn't found how to have resolved version in pom dependency management

And finally I don't need to rely and introduce complexity of the `flatten-maven-plugin` while I only need to expose the calculated version in properties, which can be easily reused in the project

**Comment by McFoggy** [comment]
I cannot release at the moment, sonatype oss seems down ; timeouts occur while deploying. Stay tuned for 1.7.0.

**Comment by McFoggy** [comment]
still no `1.7.0` deployment possible due to sonatype OSSRH issues, see https://issues.sonatype.org/browse/OSSRH-62435

**Comment by dfournie** [comment]
@McFoggy @michael-wirth I've updated my project with 1.7.0, thanks for this feature

**Edit** : for information found some typo in the README. The parameter is named `jgitver.jgitver.resolve-project-version` in the README but it is `jgitver.resolve-project-version`

**Pull request merged**
